global_defs {
    router_id DNSDIST_B1
    enable_script_security
    script_user root
}

vrrp_script chk_dnsdist {
    script "/usr/local/bin/check-dnsdist.sh"
    interval 2
    timeout 2
    rise 2
    fall 2
    weight -20
}

vrrp_instance VI_DNS_B {
    state MASTER
    interface eth0
    virtual_router_id 52
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass DNSVIPB
    }
    virtual_ipaddress {
        10.10.20.10/24
    }
    track_script {
        chk_dnsdist
    }
}
