----------------------------------------------------
-- Global
----------------------------------------------------
setLocal("0.0.0.0:53")
setACL({"0.0.0.0/0"})

----------------------------------------------------
-- Packet Cache
----------------------------------------------------
pc = newPacketCache(
    100000,
    {
        maxTTL=300,
        minTTL=10,
        staleTTL=60,
        temporaryFailureTTL=30,
        dontAge=false
    }
)
getPool(""):setCache(pc)

----------------------------------------------------
-- Server Selection Policy
----------------------------------------------------
setServerPolicy(wrandom)

----------------------------------------------------
-- Local Servers (Preferred)
----------------------------------------------------
newServer{
    address="10.10.10.12:53",
    name="Knot-A2",
    weight=100,
    checkType="A",
    checkName="_dns-health.domain.local"
}
newServer{
    address="10.10.10.13:53",
    name="Knot-A3",
    weight=100,
    checkType="A",
    checkName="_dns-health.domain.local"
}

----------------------------------------------------
-- Remote Backup Servers
----------------------------------------------------
newServer{
    address="10.10.20.12:53",
    name="Knot-B2",
    weight=1,
    checkType="A",
    checkName="_dns-health.domain.local"
}
newServer{
    address="10.10.20.13:53",
    name="Knot-B3",
    weight=1,
    checkType="A",
    checkName="_dns-health.domain.local"
}

----------------------------------------------------
-- Security
----------------------------------------------------
addAction(
    MaxQPSIPRule(1000),
    DropAction()
)
addAction(
    QTypeRule(DNSQType.ANY),
    RCodeAction(DNSRCode.REFUSED)
)

----------------------------------------------------
-- Web UI
----------------------------------------------------
webserver("0.0.0.0:8083")
setWebserverConfig({
    password="admin123"
})

----------------------------------------------------
-- Statistics
----------------------------------------------------
setRingBuffersSize(500000)
