server:
  listen: 10.10.20.13@53

mod-dnstap:
  - id: tap
    sink: "unix:/tmp/dnstap.sock"
    log-queries: on
    log-responses: on

key:
  - id: tsig-local-b
    algorithm: hmac-sha256
    secret: "replace_with_base64_secret"

remote:
  - id: local_primary
    address: 10.10.20.11@53
    key: tsig-local-b

acl:
  - id: allow_notify
    address: 10.10.20.11
    key: tsig-local-b
    action: notify

template:
  - id: default
    global-module: mod-dnstap/tap
    storage: /var/lib/knot
    file: "%s.zone"

zone:
  - domain: domain.local
    master: local_primary
    acl: allow_notify
