server:
  listen: 10.10.20.11@53

mod-dnstap:
  - id: tap
    sink: "unix:/tmp/dnstap.sock"
    log-queries: on
    log-responses: on

key:
  - id: tsig-site-sync
    algorithm: hmac-sha256
    secret: "replace_with_base64_secret"
  - id: tsig-master-slave
    algorithm: hmac-sha256
    secret: "replace_with_base64_secret"

remote:
  - id: site_b_slave1
    address: 10.10.20.12@53
    key: tsig-master-slave
  - id: site_b_slave2
    address: 10.10.20.13@53
    key: tsig-master-slave
  - id: site_a_primary
    address: 10.10.10.11@53
    key: tsig-site-sync

acl:
  - id: allow_transfer_local
    address: [10.10.20.12, 10.10.20.13]
    key: tsig-master-slave
    action: transfer
  - id: allow_transfer_remote
    #address: 10.10.10.11 # Commented for restrict remote IP for NATed Network, Uncomment for same networks
    key: tsig-site-sync
    action: transfer
  - id: allow_notify_from_a
    address: 10.10.20.1  # Gateway IP set for Nated Network, Set to Source(Knot-A1 IP: 10.10.10.11) for same networks
    key: tsig-site-sync
    action: notify

template:
  - id: default
    global-module: mod-dnstap/tap
    storage: /var/lib/knot
    file: "%s.zone"

zone:
  - domain: domain.local
    master: site_a_primary # Comment this to Set it to Master, UnCommented meaning A1 is master
    notify: [site_b_slave1, site_b_slave2, site_a_primary]
    acl: [allow_transfer_local, allow_transfer_remote, allow_notify_from_a]
